version: '2'

services:

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: logstash:7.17.10
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "50000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.17.10
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
      - ./kibana/translations/:/usr/share/kibana/src/legacy/core_plugins/kibana/translations
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:9.3.26
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    # healthcheck:
    #   test: [ "CMD", "nc", "-z", "localhost", "3000" ]
      
  # elasticsearch-head:
  #   image: mobz/elasticsearch-head:5
  #   ports:
  #     - "9100:9100"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch



  zabbix-mysql:
    image: mysql:8.0.33
    container_name: zabbix-mysql
    ports: 
      - '3366:3306'
    networks:
      - elk
    environment:
      - MYSQL_ROOT_PASSWORD="123456"
    volumes:
      - ./mysql_data:/var/lib/mysql
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:centos-5.0-latest
    container_name: zabbix-server-mysql
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD="123456"
    ports:
      - '10051:10051'
    networks:
      - elk
    links:
      - zabbix-mysql
    depends_on:
      - zabbix-mysql


  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:centos-5.0-latest
    container_name: zabbix-web-nginx-mysql
    volumes:
      - ./zabbix/simkai.ttf:/usr/share/zabbix/fonts/simkai.ttf 
      - ./zabbix/defines.inc.php:/usr/share/zabbix/include/defines.inc.php
      - ./zabbix/nginx.conf:/etc/zabbix/nginx.conf
      - ./zabbix/htpasswd:/etc/nginx/.htpasswd
    
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD="123456"
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - PHP_TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    networks:
      - elk
    links:
      - zabbix-mysql
      - zabbix-server-mysql
      - kibana
    depends_on:
      - zabbix-mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config:/etc/prometheus

    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:9.3.16
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    # volumes:
    #   - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

networks:
  elk:
    driver: bridge
