version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    # build:
    #   context: kibana/
    image: docker.elastic.co/kibana/kibana:6.7.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
      - ./kibana/translations/:/usr/share/kibana/src/legacy/core_plugins/kibana/translations
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - "9100:9100"
    networks:
      - elk
    depends_on:
      - elasticsearch



  zabbix-mysql:
    image: mysql:5.7.19
    # container_name: zabbix-mysql
    ports: 
      - '3306'
    networks:
      - elk
    environment:
      - MYSQL_ROOT_PASSWORD="123456"
    volumes:
      - ./mysql_data:/var/lib/mysql
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:centos-4.2.1
    # container_name: zabbix-web-nginx-mysql
    volumes:
      - ./zabbix/simkai.ttf:/usr/share/zabbix/fonts/simkai.ttf 
      - ./zabbix/defines.inc.php:/usr/share/zabbix/include/defines.inc.php
      - ./zabbix/nginx.conf:/etc/zabbix/nginx.conf
    
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD="123456"
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - PHP_TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    networks:
      - elk
    links:
      - zabbix-mysql
      - zabbix-server-mysql
      - kibana
    depends_on:
      - zabbix-mysql
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:centos-4.2.1
    # container_name: zabbix-server-mysql
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD="123456"
    ports:
      - '10051:10051'
    networks:
      - elk
    links:
      - zabbix-mysql
    depends_on:
      - zabbix-mysql

networks:
  elk:
    driver: bridge
